general:
  exp_name: 'fmdda_01_base'
  pth_dir: 'pths/'
  save_dir: 'results/'

  dateset_class: 'SingleStackDataset'
  raw_path: 'data/FMDD/actin-confocal-lowsnr.tif'
  gt_path: 'data/FMDD/actin-confocal-highsnr.tif'

  norm: 'hard'
  mask_ratio: 0.1

train:
  crop_size: 1024
  batch_size: 1
  num_epochs: 700
  shuffling_epoch: 100
  iter_save: 100
  lr: 0.0004

  apply_shuffling: False
  std_kernel_size: 3
  shuffling_tile_size: 4
  masking_threshold: 0.1

eval:
  load_pth: 'epoch_700.pth'
  num_predictions: 10
  alignment: True