general:
  exp_name: 'fmdwf_01'
  pth_dir: 'pths/'
  save_dir: 'results/'

  dateset_class: 'MultipleStackDataset'
  raw_dir: 'data/FMD/WideField/raw'
  gt_dir: 'data/FMD/WideField/gt'

  norm: 'soft'
  mask_ratio: 0.1

train:
  crop_size: 512
  batch_size: 1
  num_epochs: 700
  shuffling_epoch: 100
  iter_save: 100
  lr: 0.0004

  apply_shuffling: True
  std_kernel_size: 3
  shuffling_tile_size: 4
  masking_threshold: 0.1

eval:
  load_pth: 'epoch_500.pth'
  num_predictions: 10
  alignment: False