general:
  exp_name: lys_fused_rc3_02
  pth_dir: 'pths/'
  save_dir: 'results/'

  # dateset_class: 'MultipleStackDataset'
  dateset_class: 'ContinuousStackDataset'
  raw_dir: 'data/3DRCAN_Lys/raw'
  gt_dir: 'data/3DRCAN_Lys/gt'

  norm: 'hard'
  mask_ratio: 0.2

train:
  crop_size: null
  batch_size: 1
  num_epochs: 200
  shuffling_epoch: 20
  iter_save: 25
  lr: 0.0004

  apply_shuffling: False
  std_kernel_size: 2
  shuffling_tile_size: 4
  masking_threshold: 0.1

  fus_num: 3
  random_fus: True

eval:
  load_pth: 'epoch_100.pth'
  num_predictions: 10
  alignment: True